In [19]:
import numpy as np

1.**Data Creation** : Create suitable arrays to represent students, subjects, and their marks.

In [20]:
marks=np.random.randint(25,95,20).reshape(5,4)        #students=5 , subjects=4
print(marks)


[[64 74 87 62]
 [88 40 46 34]
 [47 87 75 59]
 [81 64 65 71]
 [84 25 45 62]]


2.**Data Exploration**:Explore the properties of these arrays — such as their dimensions, size, and structure

In [21]:
print("dimension:", marks.ndim)                    #dimension of the given array
print("size:", marks.size )                        #number of elements present in given array
print("Shape:", marks.shape)                       #shape for give array  i.e: (rows, col)
print("data types:", marks.dtype)                  # gives type of the array elements

dimension: 2
size: 20
Shape: (5, 4)
data types: int64


3.**Data Transformation**:Perform necessary reshaping and reorganization of the data to suit various operations



In [22]:
reshaped_marks=marks.flatten()                     # reshaping 2D into 1D
print("reshaped marks:",reshaped_marks )

reshaped marks: [64 74 87 62 88 40 46 34 47 87 75 59 81 64 65 71 84 25 45 62]


4.**Data Combination**:Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset

In [23]:
new_student_marks=np.array([[32,64,81,49]])                                   #Adding new student marks
updated_newstud_marks=np.vstack([marks, new_student_marks])
print(updated_newstud_marks)



[[64 74 87 62]
 [88 40 46 34]
 [47 87 75 59]
 [81 64 65 71]
 [84 25 45 62]
 [32 64 81 49]]


In [24]:
new_subject=np.array([[39], [24], [73], [52],[48], [59]])                      #Adding new subject marks for each students
updated_subject_marks=np.hstack([updated_newstud_marks, new_subject])
print(updated_subject_marks)

[[64 74 87 62 39]
 [88 40 46 34 24]
 [47 87 75 59 73]
 [81 64 65 71 52]
 [84 25 45 62 48]
 [32 64 81 49 59]]


5.**Data Modification**:Apply operations to update marks, remove data, or identify unique information

In [25]:
updated_newstud_marks[:,1]=updated_newstud_marks[:,1]+5      #increase marks of all students in col indext 1 by 5
print(updated_newstud_marks)

[[64 79 87 62]
 [88 45 46 34]
 [47 92 75 59]
 [81 69 65 71]
 [84 30 45 62]
 [32 69 81 49]]


In [26]:
updated_newstud_marks[1,0]=92                               #update a specific student's marks
print(updated_newstud_marks)

[[64 79 87 62]
 [92 45 46 34]
 [47 92 75 59]
 [81 69 65 71]
 [84 30 45 62]
 [32 69 81 49]]


In [27]:
removed_stud=np.delete(updated_newstud_marks,3, axis=0)   #remove a student of 3rd row index
print("removed student : \n",removed_stud)

removed_subject=np.delete(marks, 1, axis=1)              #removed a subject of 1st col index
print("\n removed subjects:\n",removed_subject)

removed student : 
 [[64 79 87 62]
 [92 45 46 34]
 [47 92 75 59]
 [84 30 45 62]
 [32 69 81 49]]

 removed subjects:
 [[64 87 62]
 [88 46 34]
 [47 75 59]
 [81 65 71]
 [84 45 62]]


In [28]:
unique_marks=np.unique(marks)
print( "unique marks:",unique_marks)
high_score=marks[marks>85]
print("high score:",high_score)

unique marks: [25 34 40 45 46 47 59 62 64 65 71 74 75 81 84 87 88]
high score: [87 88 87]


6.**Data Type Handling** :Demonstrate how the same data can exist in different data types and how changes affect results

In [29]:
type_casting=removed_stud.astype(dtype='float')     #covert int to float
print(type_casting)

type_cast_str=removed_stud.astype(dtype='str')      #covert int to str
print(type_cast_str)

type_cast_set=removed_stud.astype(dtype='object')   #convert into to object(list)
print(type_cast_set)


[[64. 79. 87. 62.]
 [92. 45. 46. 34.]
 [47. 92. 75. 59.]
 [84. 30. 45. 62.]
 [32. 69. 81. 49.]]
[['64' '79' '87' '62']
 ['92' '45' '46' '34']
 ['47' '92' '75' '59']
 ['84' '30' '45' '62']
 ['32' '69' '81' '49']]
[[64 79 87 62]
 [92 45 46 34]
 [47 92 75 59]
 [84 30 45 62]
 [32 69 81 49]]


7.**Copy and View Behavior**:Show the difference between creating a full copy of an array and creating a view of the same data

In [30]:
marks_view=marks.view()                     #changes made to the view are reflected in the original array
marks_view[0,0]=100
print("After editing view:\n")
print("Original marks:\n",marks)
print("\nmarks view:\n",marks_view)

After editing view:

Original marks:
 [[100  74  87  62]
 [ 88  40  46  34]
 [ 47  87  75  59]
 [ 81  64  65  71]
 [ 84  25  45  62]]

marks view:
 [[100  74  87  62]
 [ 88  40  46  34]
 [ 47  87  75  59]
 [ 81  64  65  71]
 [ 84  25  45  62]]


In [32]:
marks_copy=marks.copy()                        #Changes made to the copy do not affect the original array
marks_copy[1,1]=900
print("After edting copy:\n")
print("Original_marks :\n",marks)
print("\ncopyed marks:\n",marks_copy)

After edting copy:

Original_marks :
 [[100  74  87  62]
 [ 88  40  46  34]
 [ 47  87  75  59]
 [ 81  64  65  71]
 [ 84  25  45  62]]

copyed marks:
 [[100  74  87  62]
 [ 88 900  46  34]
 [ 47  87  75  59]
 [ 81  64  65  71]
 [ 84  25  45  62]]
